# Generated by Django 5.2.1 on 2026-03-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0005_alter_calculation_user_delete_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
