# Generated by Django 5.2.1 on 2026-03-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0002_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
